name: Bonsai Request Rebuild

on:
  workflow_run:
    workflows: 
      - goreleaser
      - Go Test
    types:
      - completed

jobs:
  bonsai-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: request bonsai rebuild
        continue-on-error: true
        run: >
          curl -v -XPOST
          -H "X-GitHub-Token: ${{ secrets.GITHUB_TOKEN }}"
          --url "https://bonsai-asset-index-staging.herokuapp.com/assets/${{ github.repository }}/build"
