name: Bonsai

on:
  workflow_run:
    workflows: 
      - goreleaser
      - Go Test
    types:
      - completed

jobs:
  bonsai-recompile:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: get versions
        continue-on-error: true
        run: >
          curl -v -XGET
          -H "X-GitHub-Token: ${{ secrets.GITHUB_TOKEN }}"
          --url "https://bonsai-asset-index-staging.herokuapp.com/assets/${{ github.repository }}"
      - name: bonsai-webhook
        continue-on-error: true
        run: echo "Trigger recompile on 'completed' workflow_job event matching workflow_job.name 'bonsai-recompile' and workflow.name 'bonsai'"
