name: Bonsai Request Rebuild

on:
  workflow_run:
    workflows: 
      - goreleaser
      - Go Test
    types:
      - completed

jobs:
  bonsai-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: get versions
        continue-on-error: true
        run: >
          curl -v -XGET
          -H "X-GitHub-Token: ${{ secrets.GITHUB_TOKEN }}"
          --url "https://bonsai-asset-index-staging.herokuapp.com/assets/${{ github.repository }}"
      - name: get auth user
        continue-on-error: true
        run: >
          curl -v -XGET
          -H 'Authorization: bearer ${{ secrets.GITHUB_TOKEN }}'
          --url "https://api.github.com/user"
      - name: get auth user repos
        continue-on-error: true
        run: >
          curl -v -XGET
          -H 'Authorization: bearer ${{ secrets.GITHUB_TOKEN }}'
          --url "https://api.github.com/users/repos/"
      - name: get auth scopes
        continue-on-error: true
        run: >
          curl -s  -o /dev/null -D - 
          -H 'Authorization: bearer ${{ secrets.GITHUB_TOKEN }}'
          --url "https://api.github.com/repos/${{ github.repository }}"
      - name: request bonsai rebuild using provided secret
        continue-on-error: true
        run: >
          curl -v -XPOST
          -H "X-GitHub-Token: ${{ secrets.GITHUB_TOKEN }}"
          --url "https://bonsai-asset-index-staging.herokuapp.com/assets/${{ github.repository }}/build"
      - name: request bonsai rebuild using added secret
        continue-on-error: true
        run: >
          curl -v -XPOST
          -H "X-GitHub-Token: ${{ secrets.BONSAI_GITHUB_TOKEN }}"
          --url "https://bonsai-asset-index-staging.herokuapp.com/assets/${{ github.repository }}/build"
